apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
  name: vault-tls
  namespace: vault
spec:
  dnsNames:
    - vault.check-consulting.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: zero-ssl-devops
  secretName: vault.check-consulting.net.tls
  usages:
    - digital signature
    - key encipherment