apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - certificate.yaml
  - ingress.yaml

helmCharts:
  - name: consul
    releaseName: consul
    repo: https://helm.releases.hashicorp.com
    version: 1.3.3
    valuesFile: consul-values.yaml
  - name: vault
    releaseName: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.27.0
    valuesFile: vault-values.yaml
