
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
labels:
  - pairs:
       argocd.argoproj.io/instance: cert-manager-operator
    includeSelectors: true

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    includeCRDs: true
    version: 1.14.2
    valuesFile: values.yml
