apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - certificate.yml
  - ingress.yml

helmCharts:
  - name: keycloak
    releaseName: jenkins
    repo: https://charts.bitnami.com/bitnami
    version: 18.5.0
    valuesFile: values.yml
