apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-dns
  namespace: argo-cd
spec:
  description: External DNS
  destinations:
    - namespace: external-dns
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/mchekini-check-consulting/pro-epargne-argo-cd.git'
    - 'https://charts.bitnami.com/bitnami'