apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  description: Ingress Nginx
  destinations:
    - namespace: ingress-nginx
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/mchekini-check-consulting/pro-epargne-argo-cd.git'
    - 'https://kubernetes.github.io/ingress-nginx'