apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pg-web
  namespace: argo-cd
spec:
  description: pg-web
  destinations:
    - namespace: pg-web
      name: in-cluster
  sourceRepos:
    - 'https://github.com/mchekini-check-consulting/pro-epargne-argo-cd.git'