apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pro-epargne
  namespace: argo-cd
spec:
  description: pro-epargne project
  destinations:
    - namespace: pro-epargne
      name: in-cluster
  sourceRepos:
    - 'https://github.com/mchekini-check-consulting/pro-epargne-argo-cd.git'
    - 'https://github.com/mchekini-check-consulting/pro-epargne-api.git'
    - 'https://github.com/mchekini-check-consulting/pro-epargne-admin-ui.git'
    - 'https://github.com/mchekini-check-consulting/pro-epargne-collab-ui.git'