apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argo-cd
  name: argo-cd-tls
  namespace: argo-cd
spec:
  dnsNames:
    - argo-cd.check-consulting.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt-prd
  secretName: argo-cd.check-consulting.net.tls
  usages:
    - digital signature
    - key encipherment