
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd
labels:
  - pairs:
       argocd.argoproj.io/instance: argo-cd-operator
    includeSelectors: true

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/crds/application-crd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/crds/applicationset-crd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/crds/appproject-crd.yaml
  - certificate.yml
  - ingress.yaml


helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argo-cd
    includeCRDs: false
    version: 6.0.6
    valuesFile: values.yml
