apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins

resources:
  - certificate.yaml
  - ingress.yaml


helmCharts:
  - name: jenkins
    releaseName: jenkins
    repo: https://charts.jenkins.io
    version: 5.0.13
    valuesFile: values.yml