apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: said-nginx-tls
spec:
  dnsNames:
    - said.check-consulting.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt-prd
  secretName: said.check-consulting.net.tls
  usages:
    - digital signature
    - key encipherment
