apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      application: front
  template:
    metadata:
      name: nginx
      labels:
        application: front
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 0
          readinessProbe:
            httpGet:
              port: 80
              path: /
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 60




