apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy

spec:
  replicas: 3
  selector:
    matchLabels:
      application: front
  template:
    metadata:
      name: nginx
      labels:
        application: front
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP

