apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pro-epargne-api-prd
spec:
  destination:
    name: in-cluster
    namespace: pro-epargne
  project: pro-epargne
  source:
    repoURL: 'https://github.com/mchekini-check-consulting/pro-epargne-argo-cd.git'
    path: '00-namespaces/prd'
  sources:
    - repoURL: 'https://github.com/mchekini-check-consulting/pro-epargne-argo-cd.git'
      targetRevision: master
      path: '40-applications/pro-epargne/pro-epargne-api/prd'
      ref: helmValues
    - repoURL: "https://github.com/mchekini-check-consulting/pro-epargne-api.git"
      targetRevision: "1bfb88d51e5f136adbfd8204ecea2058e17a01dc"
      path: "helm-chart"
      helm:
        releaseName: "pro-epargne-api"
        valueFiles:
          - $helmValues/values.yml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true