apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pro-epargne-api-prd
spec:
  destination:
    name: in-cluster
    namespace: pro-epargne
  project: pro-epargne
  sources:
    - repoURL: "https://github.com/mchekini-check-consulting/pro-epargne-api.git"
      targetRevision: develop
      path: "helm-chart"
      helm:
        releaseName: "pro-epargne-api"
        valueFiles:
          - $helmValues/40-applications/pro-epargne/pro-epargne-api/prd/values.yml
    - repoURL: 'https://github.com/mchekini-check-consulting/pro-epargne-argo-cd.git'
      targetRevision: master
      ref: helmValues
  syncPolicy:
    automated:
      prune: false
      selfHeal: true